spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/myshop?serverTimezone=JST
    username: root
    password: 
    
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    
logging:
  level:
    org:
      springframework: WARN
    com.internous.practice.model.mapper: DEBUG 